kind: pipeline
type: kubernetes
name: default

metadata:
  namespace: git

steps:
  - name: build
    image: docker
    privileged: true
    environment:
      TOKEN:
        from_secret: registry_token
    commands:
      - dockerd &
      - docker login -u registry -p $TOKEN registry.v0l.io
      - docker buildx build --push -t registry.v0l.io/lnvps-api:latest . -f lnvps_api/Dockerfile
      - docker buildx build --push -t registry.v0l.io/lnvps-api-admin:latest . -f lnvps_api_admin/Dockerfile
      - kill $(cat /var/run/docker.pid)
