db: "mysql://root:root@localhost:3376/lnvps"
lnd:
  url: "https://127.0.0.1:10003"
  cert: "/home/kieran/.polar/networks/2/volumes/lnd/alice/tls.cert"
  macaroon: "/home/kieran/.polar/networks/2/volumes/lnd/alice/data/chain/bitcoin/regtest/admin.macaroon"
delete_after: 3
provisioner:
  proxmox:
    read_only: false
    qemu:
      bios: "ovmf"
      machine: "q35"
      os_type: "l26"
      bridge: "vmbr0"
      cpu: "host"
      vlan: 100
      kvm: false