//! Tunnel pools: where inner tunnel addresses are allocated from.
//!
//! A pool is to tunnels what an `ip_range` is to guest addresses — a block to
//! carve links out of, scoped to a region, attached to the route server that
//! terminates them. Marketplace nodes are the first consumer: a node's guests
//! use LNVPS addresses, so their traffic has to reach an LNVPS route server
//! before it reaches the internet, and that is a peer on one of these pools.
//!
//! Under the `router` resource, because a pool is part of a route server's
//! configuration and anyone who can edit the router can already reconfigure the
//! same interface by hand.

use axum::extract::{Path, Query, State};
use axum::routing::get;
use axum::{Json, Router};
use chrono::{DateTime, Utc};
use ipnetwork::IpNetwork;
use serde::{Deserialize, Serialize};

use lnvps_api_common::{
    ApiData, ApiError, ApiPaginatedData, ApiPaginatedResult, ApiResult, WorkJob,
    deserialize_from_str_optional, generate_wireguard_keypair,
};
use lnvps_db::{AdminAction, AdminResource, LNVpsDb, TunnelPool};

use crate::admin::model::JobResponse;

use crate::admin::RouterState;
use crate::admin::auth::AdminAuth;

pub fn router() -> Router<RouterState> {
    Router::new()
        .route(
            "/api/admin/v1/tunnel_pools",
            get(admin_list_tunnel_pools).post(admin_create_tunnel_pool),
        )
        .route(
            "/api/admin/v1/tunnel_pools/{id}",
            get(admin_get_tunnel_pool)
                .patch(admin_update_tunnel_pool)
                .delete(admin_delete_tunnel_pool),
        )
        .route(
            "/api/admin/v1/tunnel_pools/{id}/sync",
            axum::routing::post(admin_sync_tunnel_pool),
        )
}

/// Point-to-point prefix lengths, matching the allocator. A pool's capacity is
/// counted in links, not addresses, because a link is what a node consumes.
const LINK_PREFIX_V4: u8 = 31;
const LINK_PREFIX_V6: u8 = 127;

#[derive(Serialize, Debug)]
pub struct AdminTunnelPoolInfo {
    pub id: u64,
    pub router_id: u64,
    pub router_name: String,
    pub region_id: u64,
    pub region_name: String,
    pub name: String,
    /// The WireGuard interface LNVPS configures on the route server.
    pub interface: String,
    /// The address peers send to. Not the router's management URL.
    pub listen_addr: String,
    /// The UDP port the interface listens on, and the port peers dial. Unique
    /// per route server: an interface listens on every local address at its
    /// port, so two of them collide over the port, not the address.
    pub listen_port: u16,
    /// What a peer dials, derived from the two above so the endpoint handed out
    /// cannot disagree with the socket that was configured.
    pub endpoint: String,
    /// The interface's public key, hex. Public by construction; the private
    /// half is generated by LNVPS, stored encrypted, and never returned.
    pub public_key: String,
    pub cidr4: Option<String>,
    pub cidr6: Option<String>,
    pub keepalive: Option<u16>,
    pub mtu: u16,
    pub enabled: bool,
    /// Links already carved out of this pool.
    pub links_used: u64,
    /// Links the smaller of the two blocks can supply. A dual-stack pool hands
    /// out one link of each family together, so the v4 block running out ends
    /// allocation even with v6 space left — reporting the larger number would
    /// promise capacity that cannot be handed out.
    pub links_total: u64,
    pub created: DateTime<Utc>,
}

#[derive(Deserialize, Default)]
#[serde(default)]
struct ListPoolsQuery {
    #[serde(deserialize_with = "deserialize_from_str_optional")]
    limit: Option<u64>,
    #[serde(deserialize_with = "deserialize_from_str_optional")]
    offset: Option<u64>,
    #[serde(deserialize_with = "deserialize_from_str_optional")]
    region_id: Option<u64>,
}

#[derive(Deserialize, Debug)]
pub struct CreateTunnelPoolRequest {
    /// The route server that will terminate peers from this pool.
    pub router_id: u64,
    /// The region whose nodes may be allocated from it.
    pub region_id: u64,
    pub name: String,
    /// WireGuard interface to configure on the route server, e.g. `wg-mkt0`.
    pub interface: String,
    /// The address peers send to — the route server's own address for this
    /// data plane, not its management address.
    pub listen_addr: String,
    /// UDP port the interface listens on. Defaults to 51820, but must be unique
    /// per route server: a second interface on the same port cannot come up.
    pub listen_port: Option<u16>,
    /// Optional existing private key (base64, as `wg genkey` prints), to adopt
    /// an interface that already exists. Omitted — the normal case — means
    /// LNVPS generates the keypair and configures the interface itself.
    pub private_key: Option<String>,
    /// Inner IPv4 block, e.g. `10.66.0.0/16`. At least one of the two blocks
    /// is required.
    pub cidr4: Option<String>,
    /// Inner IPv6 block, e.g. `fd00:66::/48`.
    pub cidr6: Option<String>,
    pub keepalive: Option<u16>,
    /// Defaults to 1420 — 1500 less WireGuard's overhead.
    pub mtu: Option<u16>,
    pub enabled: Option<bool>,
}

#[derive(Deserialize, Debug, Default)]
pub struct UpdateTunnelPoolRequest {
    /// The pool's `router_id` is deliberately absent: moving a pool to another
    /// route server would leave every tunnel carved from it pointing at an
    /// interface that does not exist there.
    pub region_id: Option<u64>,
    pub name: Option<String>,
    pub interface: Option<String>,
    pub listen_addr: Option<String>,
    pub listen_port: Option<u16>,
    /// Replace the interface's key. Omitted leaves it alone; `""` (or any
    /// blank value) generates a fresh keypair.
    ///
    /// Re-keying is disruptive on purpose — every node holding the old public
    /// key stops connecting until it re-reads its configuration — so it is
    /// never done implicitly by an unrelated edit.
    pub private_key: Option<String>,
    #[serde(
        default,
        deserialize_with = "lnvps_api_common::deserialize_nullable_option"
    )]
    pub cidr4: Option<Option<String>>,
    #[serde(
        default,
        deserialize_with = "lnvps_api_common::deserialize_nullable_option"
    )]
    pub cidr6: Option<Option<String>>,
    #[serde(
        default,
        deserialize_with = "lnvps_api_common::deserialize_nullable_option"
    )]
    pub keepalive: Option<Option<u16>>,
    pub mtu: Option<u16>,
    pub enabled: Option<bool>,
}

/// How many point-to-point links `cidr` can supply, saturating: a /48 of IPv6
/// holds more /127s than a `u64` can count, and the exact figure is not the
/// point once it is that large.
fn link_capacity(cidr: Option<&str>) -> Option<u64> {
    let net: IpNetwork = cidr?.parse().ok()?;
    let link_prefix = if net.is_ipv4() {
        LINK_PREFIX_V4
    } else {
        LINK_PREFIX_V6
    };
    if net.prefix() > link_prefix {
        return Some(0);
    }
    let bits = link_prefix - net.prefix();
    Some(if bits >= 64 { u64::MAX } else { 1u64 << bits })
}

async fn pool_info(
    db: &std::sync::Arc<dyn LNVpsDb>,
    pool: TunnelPool,
) -> Result<AdminTunnelPoolInfo, ApiError> {
    let router = db.get_router(pool.router_id).await?;
    let region = db.get_host_region(pool.region_id).await?;
    let links_used = db.list_tunnels_in_pool(pool.id).await?.len() as u64;

    // The binding constraint, not the roomier block: a dual-stack pool hands
    // out both families together.
    let links_total = [
        link_capacity(pool.cidr4.as_deref()),
        link_capacity(pool.cidr6.as_deref()),
    ]
    .into_iter()
    .flatten()
    .min()
    .unwrap_or(0);

    // Derived, never stored, so what a peer is told to dial cannot disagree
    // with the socket that was configured.
    let endpoint = pool.endpoint();

    Ok(AdminTunnelPoolInfo {
        id: pool.id,
        router_id: pool.router_id,
        router_name: router.name,
        region_id: pool.region_id,
        region_name: region.name,
        name: pool.name,
        interface: pool.interface,
        listen_addr: pool.listen_addr,
        listen_port: pool.listen_port,
        endpoint,
        public_key: hex::encode(pool.public_key),
        cidr4: pool.cidr4,
        cidr6: pool.cidr6,
        keepalive: pool.keepalive,
        mtu: pool.mtu,
        enabled: pool.enabled,
        links_used,
        links_total,
        created: pool.created,
    })
}

async fn admin_list_tunnel_pools(
    auth: AdminAuth,
    State(this): State<RouterState>,
    Query(params): Query<ListPoolsQuery>,
) -> ApiPaginatedResult<AdminTunnelPoolInfo> {
    auth.require_permission(AdminResource::Router, AdminAction::View)?;

    let limit = params.limit.unwrap_or(50).min(100);
    let offset = params.offset.unwrap_or(0);
    let (rows, total) = this
        .db
        .admin_list_tunnel_pools_paginated(limit, offset, params.region_id)
        .await?;

    let mut out = Vec::with_capacity(rows.len());
    for pool in rows {
        out.push(pool_info(&this.db, pool).await?);
    }
    ApiPaginatedData::ok(out, total, limit, offset)
}

async fn admin_get_tunnel_pool(
    auth: AdminAuth,
    State(this): State<RouterState>,
    Path(id): Path<u64>,
) -> ApiResult<AdminTunnelPoolInfo> {
    auth.require_permission(AdminResource::Router, AdminAction::View)?;
    let pool = this.db.get_tunnel_pool(id).await?;
    ApiData::ok(pool_info(&this.db, pool).await?)
}

/// Create a pool, then configure its interface on the route server.
async fn admin_create_tunnel_pool(
    auth: AdminAuth,
    State(this): State<RouterState>,
    Json(req): Json<CreateTunnelPoolRequest>,
) -> ApiResult<AdminTunnelPoolInfo> {
    auth.require_permission(AdminResource::Router, AdminAction::Create)?;
    let pool = create_tunnel_pool(&this.db, &req).await?;
    // The row is the desired state and the interface is realised from it, so a
    // route server that is unreachable right now delays the interface rather
    // than losing the pool. `POST /sync` re-drives it.
    dispatch_sync(&this, pool.id).await;
    ApiData::ok(pool_info(&this.db, pool).await?)
}

pub(crate) async fn create_tunnel_pool(
    db: &std::sync::Arc<dyn LNVpsDb>,
    req: &CreateTunnelPoolRequest,
) -> Result<TunnelPool, ApiError> {
    // LNVPS generates the interface's key unless an existing one is being
    // adopted. An admin pasting a public key could describe an interface but
    // never create one.
    let (private_key, public_key) = key_material(req.private_key.as_deref())?;
    let cidr4 = parse_block(req.cidr4.as_deref(), "cidr4", true)?;
    let cidr6 = parse_block(req.cidr6.as_deref(), "cidr6", false)?;
    if cidr4.is_none() && cidr6.is_none() {
        return Err(ApiError::bad_request(
            "A pool needs at least one address block, or it can allocate nothing",
        ));
    }
    let name = required(&req.name, "name")?;
    let interface = required(&req.interface, "interface")?;
    let listen_addr = parse_listen_addr(&req.listen_addr)?;
    let listen_port = parse_listen_port(req.listen_port)?;

    let id = db
        .insert_tunnel_pool(&TunnelPool {
            id: 0,
            router_id: req.router_id,
            region_id: req.region_id,
            name,
            interface,
            listen_addr,
            listen_port,
            private_key: private_key.into(),
            public_key,
            cidr4,
            cidr6,
            keepalive: req.keepalive,
            mtu: req.mtu.unwrap_or(1420),
            enabled: req.enabled.unwrap_or(true),
            created: Utc::now(),
        })
        .await?;
    Ok(db.get_tunnel_pool(id).await?)
}

/// Queue the interface push. A failure to *queue* is logged rather than
/// returned: the pool is already stored, and reporting an error for a
/// successful write would invite an admin to create it again.
async fn dispatch_sync(this: &RouterState, pool_id: u64) {
    if let Err(e) = this
        .work_commander
        .send(WorkJob::SyncTunnelPool { pool_id })
        .await
    {
        log::error!("Failed to queue tunnel pool sync for pool {pool_id}: {e}");
    }
}

/// Re-apply a pool's interface on its route server.
///
/// Needed as its own endpoint because the push can fail for reasons that have
/// nothing to do with the pool — a route server rebuilt, an SSH key rotated,
/// the box simply down — and the fix is to try again, not to edit the row.
async fn admin_sync_tunnel_pool(
    auth: AdminAuth,
    State(this): State<RouterState>,
    Path(id): Path<u64>,
) -> ApiResult<JobResponse> {
    auth.require_permission(AdminResource::Router, AdminAction::Update)?;
    // Fetch first so a missing pool is a 404 rather than a job that fails later.
    let _ = this.db.get_tunnel_pool(id).await?;
    let job_id = this
        .work_commander
        .send(WorkJob::SyncTunnelPool { pool_id: id })
        .await?;
    ApiData::ok(JobResponse { job_id })
}

/// Resolve the key material for a pool: adopt the supplied private key, or
/// generate one. The public half is always **derived**, never accepted, so the
/// pair cannot be stored disagreeing with itself.
fn key_material(private_key: Option<&str>) -> Result<(String, Vec<u8>), ApiError> {
    match private_key.map(str::trim).filter(|k| !k.is_empty()) {
        Some(key) => {
            let public = lnvps_api_common::wireguard_public_key(key)
                .map_err(|e| ApiError::bad_request(e.to_string()))?;
            Ok((key.to_string(), public))
        }
        None => {
            let pair = generate_wireguard_keypair().map_err(ApiError::internal)?;
            Ok((pair.private_key, pair.public_key))
        }
    }
}

async fn admin_update_tunnel_pool(
    auth: AdminAuth,
    State(this): State<RouterState>,
    Path(id): Path<u64>,
    Json(req): Json<UpdateTunnelPoolRequest>,
) -> ApiResult<AdminTunnelPoolInfo> {
    auth.require_permission(AdminResource::Router, AdminAction::Update)?;
    let pool = update_tunnel_pool(&this.db, id, &req).await?;
    dispatch_sync(&this, pool.id).await;
    ApiData::ok(pool_info(&this.db, pool).await?)
}

pub(crate) async fn update_tunnel_pool(
    db: &std::sync::Arc<dyn LNVpsDb>,
    id: u64,
    req: &UpdateTunnelPoolRequest,
) -> Result<TunnelPool, ApiError> {
    let mut pool = db.get_tunnel_pool(id).await?;

    if let Some(region_id) = req.region_id {
        pool.region_id = region_id;
    }
    if let Some(name) = &req.name {
        pool.name = required(name, "name")?;
    }
    if let Some(interface) = &req.interface {
        pool.interface = required(interface, "interface")?;
    }
    if let Some(listen_addr) = &req.listen_addr {
        pool.listen_addr = parse_listen_addr(listen_addr)?;
    }
    if let Some(listen_port) = req.listen_port {
        pool.listen_port = parse_listen_port(Some(listen_port))?;
    }
    if req.private_key.is_some() {
        // Re-keying cuts every node holding the old public key until it
        // re-reads its configuration, so it only happens when the field is
        // present — never as a side effect of renaming a pool.
        let (private_key, public_key) = key_material(req.private_key.as_deref())?;
        pool.private_key = private_key.into();
        pool.public_key = public_key;
    }
    if let Some(cidr4) = &req.cidr4 {
        pool.cidr4 = parse_block(cidr4.as_deref(), "cidr4", true)?;
    }
    if let Some(cidr6) = &req.cidr6 {
        pool.cidr6 = parse_block(cidr6.as_deref(), "cidr6", false)?;
    }
    if let Some(keepalive) = req.keepalive {
        pool.keepalive = keepalive;
    }
    if let Some(mtu) = req.mtu {
        pool.mtu = mtu;
    }
    if let Some(enabled) = req.enabled {
        pool.enabled = enabled;
    }

    // Shrinking a block below what is already handed out would leave live
    // tunnels outside their own pool, which the allocator would then hand to
    // somebody else.
    let allocated = db.list_tunnels_in_pool(id).await?;
    for tunnel in &allocated {
        for (addr, block, field) in [
            (tunnel.address4.as_deref(), pool.cidr4.as_deref(), "cidr4"),
            (tunnel.address6.as_deref(), pool.cidr6.as_deref(), "cidr6"),
        ] {
            let Some(addr) = addr else { continue };
            let parsed: IpNetwork = addr.parse().map_err(|_| {
                ApiError::new(format!("Tunnel {} has an unparseable address", tunnel.id))
            })?;
            let contained = block
                .and_then(|b| b.parse::<IpNetwork>().ok())
                .is_some_and(|b| b.contains(parsed.ip()));
            if !contained {
                return Err(ApiError::bad_request(format!(
                    "{field} would no longer contain {addr}, which is allocated to tunnel {}. \
                     Move that tunnel before shrinking the block.",
                    tunnel.id
                )));
            }
        }
    }

    db.update_tunnel_pool(&pool).await?;
    Ok(db.get_tunnel_pool(id).await?)
}

/// Delete a pool and tear its interface down.
///
/// The router and interface are captured before the row goes, because the job
/// runs afterwards and there would otherwise be nothing left to say what to
/// remove — leaving a configured interface on a route server that no record
/// mentions.
async fn admin_delete_tunnel_pool(
    auth: AdminAuth,
    State(this): State<RouterState>,
    Path(id): Path<u64>,
) -> ApiResult<()> {
    auth.require_permission(AdminResource::Router, AdminAction::Delete)?;
    // Fetch first so a missing pool is a 404 rather than a silent success.
    let pool = this.db.get_tunnel_pool(id).await?;
    this.db.delete_tunnel_pool(id).await?;

    if let Err(e) = this
        .work_commander
        .send(WorkJob::RemoveTunnelInterface {
            router_id: pool.router_id,
            interface: pool.interface.clone(),
        })
        .await
    {
        log::error!(
            "Deleted tunnel pool {id} but could not queue removal of interface {} on router {}: \
             {e}. The interface is still configured and must be removed by hand.",
            pool.interface,
            pool.router_id
        );
    }
    ApiData::ok(())
}

fn required(value: &str, field: &str) -> Result<String, ApiError> {
    let trimmed = value.trim();
    if trimmed.is_empty() {
        return Err(ApiError::bad_request(format!("{field} cannot be empty")));
    }
    Ok(trimmed.to_string())
}

/// Parse and normalise a block, rejecting the wrong family.
///
/// A v6 block in `cidr4` would be handed out as an IPv4 link by an allocator
/// that trusts the column, so the family is checked here rather than at
/// allocation time on somebody's first node.
fn parse_block(
    value: Option<&str>,
    field: &str,
    want_v4: bool,
) -> Result<Option<String>, ApiError> {
    let Some(value) = value.map(str::trim).filter(|v| !v.is_empty()) else {
        return Ok(None);
    };
    let net: IpNetwork = value
        .parse()
        .map_err(|_| ApiError::bad_request(format!("{field} is not a valid CIDR")))?;
    if net.is_ipv4() != want_v4 {
        return Err(ApiError::bad_request(format!(
            "{field} must be an IPv{} block",
            if want_v4 { 4 } else { 6 }
        )));
    }
    let link_prefix = if want_v4 {
        LINK_PREFIX_V4
    } else {
        LINK_PREFIX_V6
    };
    if net.prefix() > link_prefix {
        return Err(ApiError::bad_request(format!(
            "{field} is smaller than a single /{link_prefix} link"
        )));
    }
    // Store the network address, so two pools written as `10.0.0.5/24` and
    // `10.0.0.0/24` are recognisably the same block.
    Ok(Some(format!("{}/{}", net.network(), net.prefix())))
}

/// The address peers send to. A host:port pair here would be half a socket in
/// a field that already has a port of its own, so it is rejected rather than
/// silently concatenated into `1.2.3.4:51820:51820`.
fn parse_listen_addr(value: &str) -> Result<String, ApiError> {
    let addr = required(value, "listen_addr")?;
    if addr.parse::<std::net::IpAddr>().is_ok() {
        return Ok(addr);
    }
    // A hostname is allowed — route servers are usually named — but anything
    // carrying a port, a scheme or a path is a pasted URL, not an address.
    if addr.contains(':') || addr.contains('/') || addr.contains(' ') {
        return Err(ApiError::bad_request(
            "listen_addr is the address peers send to, without a port or scheme \
             (the port is listen_port)",
        ));
    }
    Ok(addr)
}

/// WireGuard's registered port, used when a pool does not pin one.
const DEFAULT_LISTEN_PORT: u16 = 51820;

/// Port 0 is not a port a peer can dial; the kernel would pick one at random.
fn parse_listen_port(value: Option<u16>) -> Result<u16, ApiError> {
    match value {
        Some(0) => Err(ApiError::bad_request(
            "listen_port must be a real port; 0 lets the kernel pick one nobody can dial",
        )),
        Some(port) => Ok(port),
        None => Ok(DEFAULT_LISTEN_PORT),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use lnvps_api_common::MockDb;
    use lnvps_db::{Router as DbRouter, RouterKind, Tunnel};
    use std::sync::Arc;

    /// A real `wg genkey` private key. Adoption of an existing interface is the
    /// only path that takes key material at all; the normal path generates it.
    const PRIVATE_KEY: &str = "aFq1uZ1B3d1QJHkkRhCsvCPPvTnJvbrMSpEuCbSFbHM=";

    async fn db() -> (Arc<dyn LNVpsDb>, u64) {
        let mock = MockDb::default();
        let router_id = {
            let mut routers = mock.router.lock().await;
            routers.insert(
                1,
                DbRouter {
                    id: 1,
                    name: "rs1".to_string(),
                    enabled: true,
                    kind: RouterKind::MockRouter,
                    url: "mock://rs".to_string(),
                    token: "t".into(),
                },
            );
            1
        };
        (Arc::new(mock), router_id)
    }

    fn create(router_id: u64) -> CreateTunnelPoolRequest {
        CreateTunnelPoolRequest {
            router_id,
            region_id: 1,
            name: "lon marketplace".to_string(),
            interface: "wg-mkt0".to_string(),
            listen_addr: "rs1.example.com".to_string(),
            listen_port: Some(51820),
            private_key: None,
            cidr4: Some("10.66.0.0/24".to_string()),
            cidr6: Some("fd00:66::/64".to_string()),
            keepalive: Some(25),
            mtu: None,
            enabled: None,
        }
    }

    #[tokio::test]
    async fn a_pool_is_created_with_sane_defaults() {
        let (db, router_id) = db().await;
        let pool = create_tunnel_pool(&db, &create(router_id)).await.unwrap();

        assert_eq!(pool.router_id, router_id);
        assert_eq!(pool.interface, "wg-mkt0");
        // The key is generated, not supplied, and the stored public half is
        // the one the stored private half produces.
        assert_eq!(
            lnvps_api_common::wireguard_public_key(pool.private_key.as_str()).unwrap(),
            pool.public_key
        );
        assert_eq!(
            pool.mtu, 1420,
            "a pool must not default to 1500: WireGuard's overhead comes off it"
        );
        assert!(pool.enabled);

        let info = pool_info(&db, pool).await.unwrap();
        assert_eq!(info.router_name, "rs1");
        assert_eq!(info.links_used, 0);
        // A /24 holds 128 /31 links; the /64 holds far more, so the v4 block is
        // what actually limits the pool.
        assert_eq!(info.links_total, 128);
    }

    /// Capacity has to reflect what can be handed out, not the roomier of the
    /// two blocks: a dual-stack pool allocates both families together.
    #[tokio::test]
    async fn capacity_is_reported_from_the_binding_block() {
        let (db, router_id) = db().await;
        let pool = create_tunnel_pool(
            &db,
            &CreateTunnelPoolRequest {
                cidr4: Some("10.66.0.0/28".to_string()),
                cidr6: Some("fd00:66::/64".to_string()),
                ..create(router_id)
            },
        )
        .await
        .unwrap();

        let info = pool_info(&db, pool).await.unwrap();
        assert_eq!(info.links_total, 8, "the /28 limits the pool to 8 links");
    }

    /// A block exactly one link wide is not a rounding error, and one that
    /// cannot hold a link reports no capacity rather than shifting negatively.
    #[test]
    fn capacity_counts_links_not_addresses() {
        assert_eq!(link_capacity(Some("10.0.0.0/31")), Some(1));
        assert_eq!(link_capacity(Some("10.0.0.0/24")), Some(128));
        assert_eq!(link_capacity(Some("fd00::/127")), Some(1));
        // Saturated rather than overflowed: the exact number of /127s in a /48
        // is not a figure anyone needs.
        assert_eq!(link_capacity(Some("fd00::/48")), Some(u64::MAX));
        // Smaller than one link. Creation refuses these, but an older row or a
        // direct database edit must not panic the listing.
        assert_eq!(link_capacity(Some("10.0.0.1/32")), Some(0));
        assert_eq!(link_capacity(Some("not-a-cidr")), None);
        assert_eq!(link_capacity(None), None);
    }

    /// A v6 block in the v4 column would be handed out as an IPv4 link by an
    /// allocator that trusts the column.
    #[tokio::test]
    async fn blocks_must_match_their_family_and_hold_a_link() {
        let (db, router_id) = db().await;
        for (cidr4, cidr6) in [
            (Some("fd00::/64"), None),
            (Some("not-a-cidr"), None),
            // A /32 cannot hold a /31, and a /128 cannot hold a /127.
            (Some("10.0.0.1/32"), None),
            (None, Some("fd00::1/128")),
            (None, Some("10.0.0.0/24")),
        ] {
            assert!(
                create_tunnel_pool(
                    &db,
                    &CreateTunnelPoolRequest {
                        cidr4: cidr4.map(str::to_string),
                        cidr6: cidr6.map(str::to_string),
                        ..create(router_id)
                    },
                )
                .await
                .is_err(),
                "accepted cidr4={cidr4:?} cidr6={cidr6:?}"
            );
        }
    }

    /// A pool with no block can allocate nothing, and would only be discovered
    /// when a node asked for a tunnel.
    #[tokio::test]
    async fn a_pool_without_a_block_is_refused() {
        let (db, router_id) = db().await;
        let err = create_tunnel_pool(
            &db,
            &CreateTunnelPoolRequest {
                cidr4: None,
                cidr6: None,
                ..create(router_id)
            },
        )
        .await
        .expect_err("a pool with nothing to allocate was created");
        assert!(
            format!("{err:?}").contains("at least one address block"),
            "{err:?}"
        );
    }

    /// The block is stored as its network address, so the same block written
    /// two ways is recognisably the same block.
    #[tokio::test]
    async fn blocks_are_normalised_to_their_network_address() {
        let (db, router_id) = db().await;
        let pool = create_tunnel_pool(
            &db,
            &CreateTunnelPoolRequest {
                cidr4: Some("10.66.0.37/24".to_string()),
                ..create(router_id)
            },
        )
        .await
        .unwrap();
        assert_eq!(pool.cidr4.as_deref(), Some("10.66.0.0/24"));
    }

    /// The listen address is an address, and the port is its own field. A
    /// pasted `host:port` here would end up concatenated into a socket with two
    /// ports.
    #[tokio::test]
    async fn a_listen_address_carrying_a_port_or_scheme_is_refused() {
        let (db, router_id) = db().await;
        for addr in [
            "rs1.example.com:51820",
            "https://rs1.example.com",
            "rs1.example.com/wg",
            "  ",
        ] {
            assert!(
                create_tunnel_pool(
                    &db,
                    &CreateTunnelPoolRequest {
                        listen_addr: addr.to_string(),
                        ..create(router_id)
                    },
                )
                .await
                .is_err(),
                "accepted listen_addr {addr}"
            );
        }

        // A bare IPv6 address is fine, and is bracketed when the endpoint is
        // rendered for a peer — which a naive host:port join gets wrong.
        let pool = create_tunnel_pool(
            &db,
            &CreateTunnelPoolRequest {
                listen_addr: "2a01:db8::1".to_string(),
                ..create(router_id)
            },
        )
        .await
        .unwrap();
        assert_eq!(pool.endpoint(), "[2a01:db8::1]:51820");
    }

    /// Port 0 lets the kernel pick a port nobody can dial, and an omitted port
    /// falls back to WireGuard's registered one rather than to zero.
    #[tokio::test]
    async fn port_zero_is_refused_and_an_omitted_port_defaults() {
        let (db, router_id) = db().await;
        assert!(
            create_tunnel_pool(
                &db,
                &CreateTunnelPoolRequest {
                    listen_port: Some(0),
                    ..create(router_id)
                },
            )
            .await
            .is_err()
        );

        let pool = create_tunnel_pool(
            &db,
            &CreateTunnelPoolRequest {
                listen_port: None,
                ..create(router_id)
            },
        )
        .await
        .unwrap();
        assert_eq!(pool.listen_port, DEFAULT_LISTEN_PORT);
    }

    /// A WireGuard interface listens on every local address at its port, so a
    /// second pool on the same port produces an interface that cannot come up —
    /// which is exactly why the socket is pinned per pool.
    #[tokio::test]
    async fn one_port_per_route_server() {
        let (db, router_id) = db().await;
        create_tunnel_pool(&db, &create(router_id)).await.unwrap();

        let err = create_tunnel_pool(
            &db,
            &CreateTunnelPoolRequest {
                interface: "wg-mkt1".to_string(),
                ..create(router_id)
            },
        )
        .await
        .expect_err("two interfaces were given the same port on one route server");
        assert!(format!("{err:?}").contains("already used"), "{err:?}");

        // A different port is what makes a second interface work.
        create_tunnel_pool(
            &db,
            &CreateTunnelPoolRequest {
                interface: "wg-mkt1".to_string(),
                listen_port: Some(51821),
                ..create(router_id)
            },
        )
        .await
        .unwrap();
    }

    /// An existing interface can be adopted by handing over its private key.
    /// The public half is always derived, never accepted, so a pool cannot be
    /// stored holding a pair that disagrees with itself.
    #[tokio::test]
    async fn an_existing_interface_can_be_adopted_by_its_private_key() {
        let (db, router_id) = db().await;
        let pool = create_tunnel_pool(
            &db,
            &CreateTunnelPoolRequest {
                private_key: Some(PRIVATE_KEY.to_string()),
                ..create(router_id)
            },
        )
        .await
        .unwrap();

        assert_eq!(pool.private_key.as_str(), PRIVATE_KEY);
        assert_eq!(
            pool.public_key,
            lnvps_api_common::wireguard_public_key(PRIVATE_KEY).unwrap()
        );
    }

    /// Re-keying an interface cuts every node holding the old public key until
    /// it re-reads its configuration, so it happens only when the field is
    /// present — never as a side effect of renaming a pool.
    #[tokio::test]
    async fn a_pool_is_only_re_keyed_when_asked() {
        let (db, router_id) = db().await;
        let pool = create_tunnel_pool(&db, &create(router_id)).await.unwrap();
        let original = pool.public_key.clone();

        let renamed = update_tunnel_pool(
            &db,
            pool.id,
            &UpdateTunnelPoolRequest {
                name: Some("renamed".to_string()),
                ..Default::default()
            },
        )
        .await
        .unwrap();
        assert_eq!(
            renamed.public_key, original,
            "an unrelated edit re-keyed the interface and cut every node on it"
        );

        // An explicit blank generates a fresh pair...
        let rolled = update_tunnel_pool(
            &db,
            pool.id,
            &UpdateTunnelPoolRequest {
                private_key: Some(String::new()),
                ..Default::default()
            },
        )
        .await
        .unwrap();
        assert_ne!(rolled.public_key, original);
        assert_eq!(
            lnvps_api_common::wireguard_public_key(rolled.private_key.as_str()).unwrap(),
            rolled.public_key
        );

        // ...and an explicit key adopts that one.
        let adopted = update_tunnel_pool(
            &db,
            pool.id,
            &UpdateTunnelPoolRequest {
                private_key: Some(PRIVATE_KEY.to_string()),
                ..Default::default()
            },
        )
        .await
        .unwrap();
        assert_eq!(adopted.private_key.as_str(), PRIVATE_KEY);
        assert_eq!(
            adopted.public_key,
            lnvps_api_common::wireguard_public_key(PRIVATE_KEY).unwrap()
        );
    }

    /// A key that is not a WireGuard key is refused here rather than pushed to
    /// a router that rejects it with no useful message.
    #[tokio::test]
    async fn a_malformed_private_key_is_refused() {
        let (db, router_id) = db().await;
        for key in ["zz", "c2hvcnQ="] {
            assert!(
                create_tunnel_pool(
                    &db,
                    &CreateTunnelPoolRequest {
                        private_key: Some(key.to_string()),
                        ..create(router_id)
                    },
                )
                .await
                .is_err(),
                "accepted private key {key}"
            );
        }
    }

    /// Two pools on one interface would each carve addresses the other does not
    /// know about, onto the same link.
    #[tokio::test]
    async fn one_interface_holds_one_pool() {
        let (db, router_id) = db().await;
        create_tunnel_pool(&db, &create(router_id)).await.unwrap();
        assert!(create_tunnel_pool(&db, &create(router_id)).await.is_err());
    }

    #[tokio::test]
    async fn a_pool_can_be_retuned_but_not_moved_off_its_router() {
        let (db, router_id) = db().await;
        let pool = create_tunnel_pool(&db, &create(router_id)).await.unwrap();

        let updated = update_tunnel_pool(
            &db,
            pool.id,
            &UpdateTunnelPoolRequest {
                enabled: Some(false),
                mtu: Some(1380),
                keepalive: Some(None),
                listen_addr: Some("rs2.example.com".to_string()),
                ..Default::default()
            },
        )
        .await
        .unwrap();
        assert!(!updated.enabled);
        assert_eq!(updated.mtu, 1380);
        assert_eq!(updated.keepalive, None);
        assert_eq!(updated.listen_addr, "rs2.example.com");

        // Every remaining field, including the ones only touched when a route
        // server is re-keyed or an interface renamed.
        let retuned = update_tunnel_pool(
            &db,
            pool.id,
            &UpdateTunnelPoolRequest {
                region_id: Some(1),
                name: Some("lon marketplace 2".to_string()),
                interface: Some("wg-mkt1".to_string()),
                listen_port: Some(51821),
                cidr6: Some(Some("fd00:67::/64".to_string())),
                ..Default::default()
            },
        )
        .await
        .unwrap();
        assert_eq!(retuned.name, "lon marketplace 2");
        assert_eq!(retuned.interface, "wg-mkt1");
        assert_eq!(retuned.listen_port, 51821);
        assert_eq!(retuned.cidr6.as_deref(), Some("fd00:67::/64"));

        // Blank is not a rename.
        for req in [
            UpdateTunnelPoolRequest {
                name: Some("  ".to_string()),
                ..Default::default()
            },
            UpdateTunnelPoolRequest {
                interface: Some("".to_string()),
                ..Default::default()
            },
        ] {
            assert!(update_tunnel_pool(&db, pool.id, &req).await.is_err());
        }
        assert_eq!(
            updated.router_id, router_id,
            "there is no way to move a pool between route servers, by design"
        );
        // An omitted field is left alone.
        assert_eq!(updated.cidr4.as_deref(), Some("10.66.0.0/24"));
    }

    /// Shrinking a block under a live allocation would leave that tunnel
    /// outside its own pool, and the allocator would hand its addresses to
    /// somebody else.
    #[tokio::test]
    async fn a_block_cannot_be_shrunk_out_from_under_an_allocation() {
        let (db, router_id) = db().await;
        let pool = create_tunnel_pool(&db, &create(router_id)).await.unwrap();
        let user_id = db.upsert_user(&[4u8; 32]).await.unwrap();
        db.insert_tunnel(&Tunnel {
            user_id,
            router_id: Some(router_id),
            pool_id: Some(pool.id),
            name: "mkt-node-1".to_string(),
            address4: Some("10.66.0.129/31".to_string()),
            address6: Some("fd00:66::1/127".to_string()),
            enabled: true,
            ..Default::default()
        })
        .await
        .unwrap();

        let err = update_tunnel_pool(
            &db,
            pool.id,
            &UpdateTunnelPoolRequest {
                cidr4: Some(Some("10.66.0.0/25".to_string())),
                ..Default::default()
            },
        )
        .await
        .expect_err("a block was shrunk under a live tunnel");
        assert!(
            format!("{err:?}").contains("allocated to tunnel"),
            "{err:?}"
        );

        // A stored address that cannot be parsed is reported rather than
        // treated as "not in the block", which would blame the wrong thing.
        let mut broken = db.list_tunnels_in_pool(pool.id).await.unwrap().remove(0);
        broken.address4 = Some("not-an-address".to_string());
        db.update_tunnel(&broken).await.unwrap();
        let err = update_tunnel_pool(
            &db,
            pool.id,
            &UpdateTunnelPoolRequest {
                cidr4: Some(Some("10.66.0.0/25".to_string())),
                ..Default::default()
            },
        )
        .await
        .expect_err("an unparseable allocation was ignored");
        assert!(
            format!("{err:?}").contains("unparseable address"),
            "{err:?}"
        );
        broken.address4 = Some("10.66.0.129/31".to_string());
        db.update_tunnel(&broken).await.unwrap();

        // Growing it is fine.
        let grown = update_tunnel_pool(
            &db,
            pool.id,
            &UpdateTunnelPoolRequest {
                cidr4: Some(Some("10.66.0.0/16".to_string())),
                ..Default::default()
            },
        )
        .await
        .unwrap();
        assert_eq!(grown.cidr4.as_deref(), Some("10.66.0.0/16"));

        // And the pool now reports the allocation.
        let info = pool_info(&db, grown).await.unwrap();
        assert_eq!(info.links_used, 1);
    }

    /// Dropping a block a live tunnel sits in is the same mistake as shrinking
    /// one.
    #[tokio::test]
    async fn a_block_cannot_be_removed_out_from_under_an_allocation() {
        let (db, router_id) = db().await;
        let pool = create_tunnel_pool(&db, &create(router_id)).await.unwrap();
        let user_id = db.upsert_user(&[4u8; 32]).await.unwrap();
        db.insert_tunnel(&Tunnel {
            user_id,
            router_id: Some(router_id),
            pool_id: Some(pool.id),
            name: "mkt-node-1".to_string(),
            address4: Some("10.66.0.1/31".to_string()),
            enabled: true,
            ..Default::default()
        })
        .await
        .unwrap();

        assert!(
            update_tunnel_pool(
                &db,
                pool.id,
                &UpdateTunnelPoolRequest {
                    cidr4: Some(None),
                    ..Default::default()
                },
            )
            .await
            .is_err()
        );
    }

    /// The handlers, through the extractors and the routes they are mounted
    /// on, including the permission they sit behind.
    #[tokio::test]
    async fn the_endpoints_serve_pool_administration() {
        use crate::admin::model::Permission;
        use lnvps_api_common::{
            ChannelWorkCommander, MockExchangeRate, VmStateCache, WorkCommander,
        };

        let (db, router_id) = db().await;
        let jobs = Arc::new(ChannelWorkCommander::new());
        let this = RouterState {
            db: db.clone(),
            work_commander: jobs.clone(),
            feedback: None,
            vm_state_cache: VmStateCache::new(),
            exchange: Arc::new(MockExchangeRate::default()),
        };
        let auth = |resource: AdminResource| AdminAuth {
            user_id: 1,
            pubkey: vec![1u8; 32],
            permissions: [
                AdminAction::View,
                AdminAction::Create,
                AdminAction::Update,
                AdminAction::Delete,
            ]
            .into_iter()
            .map(|action| Permission { resource, action })
            .collect(),
            nip98_auth: None,
        };
        let admin = || auth(AdminResource::Router);

        // A handler nothing routes to is not an endpoint.
        let _: Router<RouterState> = router();

        let created =
            admin_create_tunnel_pool(admin(), State(this.clone()), Json(create(router_id)))
                .await
                .unwrap();
        let pool_id = created.data.id;
        assert_eq!(created.data.region_name, "Mock");
        assert_eq!(created.data.endpoint, "rs1.example.com:51820");

        // Creating a pool configures the interface: the row on its own is a
        // description of something that does not exist yet.
        assert!(
            matches!(
                jobs.recv().await.unwrap().first().map(|m| &m.job),
                Some(WorkJob::SyncTunnelPool { pool_id: p }) if *p == pool_id
            ),
            "creating a pool did not push the interface to the route server"
        );

        let listed = admin_list_tunnel_pools(
            admin(),
            State(this.clone()),
            Query(ListPoolsQuery::default()),
        )
        .await
        .unwrap();
        assert_eq!(listed.total, 1);

        // Filtering by a region with no pool must return nothing, not
        // everything — an ignored filter would show an admin capacity that
        // cannot serve the region they are looking at.
        let elsewhere = admin_list_tunnel_pools(
            admin(),
            State(this.clone()),
            Query(ListPoolsQuery {
                region_id: Some(999),
                ..Default::default()
            }),
        )
        .await
        .unwrap();
        assert_eq!(elsewhere.total, 0);

        let got = admin_get_tunnel_pool(admin(), State(this.clone()), Path(pool_id))
            .await
            .unwrap();
        assert_eq!(got.data.interface, "wg-mkt0");

        let updated = admin_update_tunnel_pool(
            admin(),
            State(this.clone()),
            Path(pool_id),
            Json(UpdateTunnelPoolRequest {
                enabled: Some(false),
                ..Default::default()
            }),
        )
        .await
        .unwrap();
        assert!(!updated.data.enabled);
        // ...and an edit re-applies it, or the route server keeps serving the
        // configuration the pool used to have.
        assert!(matches!(
            jobs.recv().await.unwrap().first().map(|m| &m.job),
            Some(WorkJob::SyncTunnelPool { .. })
        ));

        // A sync can be asked for on its own, because the push fails for
        // reasons that have nothing to do with the pool — a rebuilt route
        // server, a rotated SSH key, a box that is simply down — and the fix is
        // to try again, not to edit the row.
        let job = admin_sync_tunnel_pool(admin(), State(this.clone()), Path(pool_id))
            .await
            .unwrap();
        assert!(!job.data.job_id.is_empty());
        assert!(matches!(
            jobs.recv().await.unwrap().first().map(|m| &m.job),
            Some(WorkJob::SyncTunnelPool { .. })
        ));
        assert!(
            admin_sync_tunnel_pool(admin(), State(this.clone()), Path(pool_id + 999))
                .await
                .is_err(),
            "a sync was queued for a pool that does not exist"
        );

        // Pools are route-server configuration, so they sit behind the same
        // permission as the router itself and nothing else grants them.
        let outsider = || auth(AdminResource::MarketplaceNode);
        assert!(
            admin_list_tunnel_pools(
                outsider(),
                State(this.clone()),
                Query(ListPoolsQuery::default())
            )
            .await
            .is_err()
        );
        assert!(
            admin_get_tunnel_pool(outsider(), State(this.clone()), Path(pool_id))
                .await
                .is_err()
        );
        assert!(
            admin_create_tunnel_pool(outsider(), State(this.clone()), Json(create(router_id)))
                .await
                .is_err()
        );
        assert!(
            admin_update_tunnel_pool(
                outsider(),
                State(this.clone()),
                Path(pool_id),
                Json(UpdateTunnelPoolRequest::default()),
            )
            .await
            .is_err()
        );
        assert!(
            admin_delete_tunnel_pool(outsider(), State(this.clone()), Path(pool_id))
                .await
                .is_err()
        );

        assert!(
            admin_sync_tunnel_pool(outsider(), State(this.clone()), Path(pool_id))
                .await
                .is_err()
        );

        let _ = admin_delete_tunnel_pool(admin(), State(this.clone()), Path(pool_id))
            .await
            .unwrap();
        assert!(db.get_tunnel_pool(pool_id).await.is_err());

        // Deleting the row tears the interface down too, addressed by router
        // and interface because the row it came from is already gone.
        assert!(
            matches!(
                jobs.recv().await.unwrap().first().map(|m| &m.job),
                Some(WorkJob::RemoveTunnelInterface { router_id: r, interface })
                    if *r == router_id && interface == "wg-mkt0"
            ),
            "deleting a pool left its interface configured on the route server"
        );

        // A pool that never existed is a 404, not a silent success.
        assert!(
            admin_delete_tunnel_pool(admin(), State(this.clone()), Path(pool_id))
                .await
                .is_err()
        );
    }

    /// A queue that is down must not turn a stored pool into an error the
    /// admin retries, nor hide that a deleted pool's interface is still
    /// configured on the route server.
    #[tokio::test]
    async fn a_dead_job_queue_does_not_lose_the_pool_or_hide_the_leftover() {
        use crate::admin::model::Permission;
        use lnvps_api_common::{MockExchangeRate, VmStateCache, WorkCommander, WorkJobMessage};

        struct DeadQueue;
        #[async_trait::async_trait]
        impl WorkCommander for DeadQueue {
            async fn send(&self, _job: WorkJob) -> anyhow::Result<String> {
                anyhow::bail!("queue is down")
            }
            async fn recv(&self) -> anyhow::Result<Vec<WorkJobMessage>> {
                Ok(vec![])
            }
            async fn ack(&self, _id: &str) -> anyhow::Result<()> {
                Ok(())
            }
        }

        let (db, router_id) = db().await;
        let this = RouterState {
            db: db.clone(),
            work_commander: Arc::new(DeadQueue),
            feedback: None,
            vm_state_cache: VmStateCache::new(),
            exchange: Arc::new(MockExchangeRate::default()),
        };
        let admin = AdminAuth {
            user_id: 1,
            pubkey: vec![1u8; 32],
            permissions: [
                AdminAction::View,
                AdminAction::Create,
                AdminAction::Update,
                AdminAction::Delete,
            ]
            .into_iter()
            .map(|action| Permission {
                resource: AdminResource::Router,
                action,
            })
            .collect(),
            nip98_auth: None,
        };

        // The pool is stored even though the interface could not be pushed:
        // returning an error for a successful write invites the admin to create
        // it a second time. `POST /sync` is the retry.
        let created = admin_create_tunnel_pool(
            AdminAuth { ..admin },
            State(this.clone()),
            Json(create(router_id)),
        )
        .await
        .unwrap();
        let pool_id = created.data.id;
        assert!(db.get_tunnel_pool(pool_id).await.is_ok());

        // The delete still removes the row — the alternative is a pool nobody
        // can get rid of while the queue is down — and the interface left on
        // the route server is logged loudly enough to be cleaned up by hand.
        let admin = AdminAuth {
            user_id: 1,
            pubkey: vec![1u8; 32],
            permissions: [Permission {
                resource: AdminResource::Router,
                action: AdminAction::Delete,
            }]
            .into_iter()
            .collect(),
            nip98_auth: None,
        };
        let _ = admin_delete_tunnel_pool(admin, State(this.clone()), Path(pool_id))
            .await
            .unwrap();
        assert!(db.get_tunnel_pool(pool_id).await.is_err());
    }

    /// A pool still carrying allocations cannot be deleted: those tunnels are
    /// live guest traffic.
    #[tokio::test]
    async fn a_pool_with_allocations_cannot_be_deleted() {
        let (db, router_id) = db().await;
        let pool = create_tunnel_pool(&db, &create(router_id)).await.unwrap();
        let user_id = db.upsert_user(&[4u8; 32]).await.unwrap();
        db.insert_tunnel(&Tunnel {
            user_id,
            router_id: Some(router_id),
            pool_id: Some(pool.id),
            name: "mkt-node-1".to_string(),
            address4: Some("10.66.0.1/31".to_string()),
            enabled: true,
            ..Default::default()
        })
        .await
        .unwrap();

        assert!(db.delete_tunnel_pool(pool.id).await.is_err());
    }
}
