-- Tunnels: the source of truth for what LNVPS has *assigned*.
--
-- `router_tunnel` (2026-06) is a discovery cache — "what did we last observe on
-- this router" — keyed by (router_id, name), with a `last_seen` and no key
-- material. It answers "what exists", never "what should exist, and whose is
-- it". Nothing today records that a given WireGuard peer key and inner address
-- belong to a particular customer or node, which means an allocation cannot be
-- made, audited, or reclaimed.
--
-- This table is the desired state; `router_tunnel` stays the observed state,
-- and the two are reconciled the same way host state is. Keeping them separate
-- is deliberate: an entry vanishing from a router must show up as drift, not as
-- an assignment silently disappearing.
--
-- One table serves every tunnel we terminate, rather than a WireGuard column
-- bolted onto each consumer:
--   * marketplace node data planes (guest traffic back to a route server),
--   * plain WireGuard VPNs sold to users,
--   * infrastructure peerings, including tunnels carrying BGP.
--
-- There is no `purpose` column. A tunnel sold to a user has a `user_id`; every
-- other tunnel is ours, and a marketplace node's is found through
-- `marketplace_node.tunnel_id`. A node link and a BGP transport differ in what
-- is routed over them, not in anything this table stores — and a column that
-- merely restates which reference points at the row is one more thing free to
-- disagree with it.

CREATE TABLE tunnel (
    id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,

    -- Encapsulation. Values match `router_tunnel.kind` (RouterTunnelKind:
    -- 0 = GRE, 1 = VXLAN, 2 = WireGuard) so observed and desired state can be
    -- compared without a translation table.
    kind SMALLINT UNSIGNED NOT NULL DEFAULT 2,

    -- The customer this tunnel was sold to, when it is a VPN. NULL means the
    -- tunnel is LNVPS's own — a marketplace node's data plane, or an
    -- infrastructure peering. A real FK rather than an (owner_type, owner_id)
    -- pair, so the database still enforces that the owner exists.
    user_id INTEGER UNSIGNED NULL DEFAULT NULL,

    -- The route server terminating this tunnel. NULL until one is chosen, so a
    -- tunnel can be allocated before it is placed.
    router_id INTEGER UNSIGNED NULL DEFAULT NULL,

    -- Interface/peer name we intend to configure on the router. Matches
    -- `router_tunnel.name` once realised, which is how the two are correlated.
    name VARCHAR(100) NOT NULL,

    -- The remote end's public key. Generated by the peer (node or customer) —
    -- the private half must never leave their machine, and we never hold it.
    --
    -- BINARY(32) (the raw key) rather than its base64 text: the database
    -- collation is `utf8mb4_uca1400_ai_ci`, which compares case-insensitively,
    -- while base64 is case-sensitive. A text column would let two distinct keys
    -- collide in the unique index and — far worse — let a lookup by key match a
    -- *different* peer's tunnel.
    --
    -- The server-side public key is not duplicated here: it belongs to the
    -- router's interface, and a second copy would be free to drift.
    peer_pubkey BINARY(32) NULL DEFAULT NULL,

    -- Peer's endpoint if it is reachable (`host:port`). Usually NULL: nodes and
    -- VPN clients sit behind NAT and dial out, so the router learns the
    -- endpoint from the handshake.
    peer_endpoint VARCHAR(255) NULL DEFAULT NULL,

    -- Inner addresses assigned by LNVPS (never chosen by the peer), as CIDR —
    -- typically a /31 and/or /127 point-to-point link.
    --
    -- Unique because two peers sharing an inner address is a routing collision
    -- that delivers one tenant's traffic to another. Globally unique rather
    -- than per-router: that is the stronger constraint, and it can be relaxed
    -- to a composite key if tunnel pools end up being per-route-server, whereas
    -- tightening it later would need a data migration.
    address4 VARCHAR(64) NULL DEFAULT NULL,
    address6 VARCHAR(64) NULL DEFAULT NULL,

    -- Persistent keepalive in seconds. NULL leaves it unset (the peer decides),
    -- which is what a NATed dial-out peer normally wants.
    keepalive SMALLINT UNSIGNED NULL DEFAULT NULL,

    -- Whether the tunnel should be configured on the router at all. Disabling
    -- is how a tunnel is cut without losing the allocation or its history.
    enabled BOOLEAN NOT NULL DEFAULT TRUE,

    created DATETIME NOT NULL DEFAULT NOW(),

    PRIMARY KEY (id),
    UNIQUE KEY uk_tunnel_peer_pubkey (peer_pubkey),
    UNIQUE KEY uk_tunnel_address4 (address4),
    UNIQUE KEY uk_tunnel_address6 (address6),
    KEY ix_tunnel_user (user_id),
    KEY ix_tunnel_router (router_id),

    FOREIGN KEY (user_id) REFERENCES users (id),
    FOREIGN KEY (router_id) REFERENCES router (id)
);

-- A node's data plane. Nullable because a node is registered before it is
-- given one, and unique because a tunnel terminates exactly one peer: two
-- nodes sharing it would be two machines answering to one key and address.
--
-- ON DELETE RESTRICT (the default) so a tunnel still carrying a node's guest
-- traffic cannot be deleted out from under it.
ALTER TABLE marketplace_node
    ADD COLUMN tunnel_id INTEGER UNSIGNED NULL DEFAULT NULL,
    ADD UNIQUE KEY uk_marketplace_node_tunnel (tunnel_id),
    ADD FOREIGN KEY (tunnel_id) REFERENCES tunnel (id);
